# Generated by Django 2.2.28 on 2024-04-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_marketplace', '0002_auto_20240426_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
